/**
 * Yu-Gi-Oh! Master Saga Pack Opener
 * Official Master Duel Secret Packs Database
 *
 * Adding Custom/Normal Cards to a Secret Pack:
 * You can explicitly add any standard Yu-Gi-Oh! card to a pack's featured pool
 * by adding an optional `cards` array containing its exact Card Name (string)
 * or Card ID (number).
 *
 * Example:
 * cosmic_ocean: {
 *     name: "Treasures of the Cosmic Ocean",
 *     description: "Umi, Water Support",
 *     archetypes: ["Ice Jade", "White", "Ghoti"],
 *     cards: ["Ash Blossom & Joyous Spring", 2314238] // Explicitly add Ash Blossom and a card ID to this pack!
 * }
 *
 * Excluding Cards from a Specific Secret Pack:
 * You can explicitly exclude any card from a specific secret pack's featured pool
 * by adding an optional `exclude_cards` array containing its exact Card Name (string)
 * or Card ID (number). This prevents the card from being pulled from the secret pack's
 * featured slots, and pulling this card from other packs will not trigger the unlock of this pack.
 *
 * Example:
 * cosmic_ocean: {
 *     name: "Treasures of the Cosmic Ocean",
 *     description: "Umi, Water Support",
 *     archetypes: ["Icejade", "Ghoti"],
 *     exclude_cards: ["Icejade Tremora", 99999999]
 * }
 */

const SECRET_PACKS = {
  cosmic_ocean: {
    name: "Treasures of the Cosmic Ocean",
    description: ["Icejade", "Ghoti", "Fish Support"],
    archetypes: ["Icejade", "Ghoti"],
    cards: [
      "Surface",
      "White Aura Bihamut",
      "Moray of Avarice",
      "The Most Distant, Deepest Depths",
      "White Aura Dolphin",
      "White Aura Whale",
      "White Howling",
      "Abyss Keeper",
      "White Stingray",
      "Minairuka",
      "White Mirror",
      "White Moray",
      "Whitefish Salvage",
    ],
  },
  supreme_strike: {
    name: "Supreme Strike",
    description: ["Mathmech", "Cyberse Slop"],
    archetypes: ["Mathmech"],
    cards: [
      "DPH Gendamoore",
      "Link Disciple",
      "Pendransaction",
      "RAM Clouder",
      "Balancer Lord",
      "ROM Cloudia",
      "Grid Sweeper",
      "Drastic Draw",
      "Cyberse Wizard",
      "Rebuildeer",
      "Proxy Horse",
      "Firewall Defenser",
      "One-Time Passcode",
      "Cynet Optimization",
      "Link Devotee",
      "Antialian",
      "Storm Cipher",
      "Cynet Crosswipe",
      "Cynet Rollback",
    ],
  },
  echo_chamber_nation: {
    name: "Echo Chamber Nation",
    description: ["Dogmatika", "Ritual Support"],
    archetypes: ["Dogmatika"],
    cards: [
      "The Fallen & the Virtuous",
      "The Dragon that Devours the Dogma",
      "Titaniklad the Ash Dragon",
      "Herald of the Arc Light",
      "Pre-Preparation of Rites",
      "Yakusa, Lord of the Eight Thunders",
      "Manju of the Ten Thousand Hands",
      "fallen of albaz",
      "Nadir Servant",
    ],
  },
  alba_abyss: {
    name: "Alba Abyss",
    description: ["Branded", "Springans"],
    archetypes: ["Branded"],
    cards: [
      "fusion deployment",
      "mirrorjade the iceblade dragon",
      "Lubellion the searing dragon",
      "Alba-lenatus the abyss dragon",
      "Springans Merrymaker",
      "Incredible ecclesia, the virtuous",
      "the golden swordsoul",
      "Albaz the ashen",
      "Sprind the irondash Dragon",
      "Tri-brigade Kitt",
      "Albion the Shrouded dragon",
      "Springans Kitt",
      "Dogmatika Nation",
      "Dogmatika Punishment",
      "Dogmatika Encounter",
      "Springans Call!",
      "Springans Blast!",
      "Dogmatikaturgy",
    ],
  },
  supernatural_elements: {
    name: "Supernatural Elements",
    description: ["Monarch", "ElementSaber"],
    archetypes: ["Monarch", "Vassal", "Elemental Lord", "Elementsaber"],
    cards: [
      "Eidos the Underworld Squire",
      "Elemental Training",
      "Edea the Heavenly Squire",
      "Tessera the Primal Squire",
    ],
    exclude_cards: [
      "Mobius the Frost Monarch",
      "Caius the Shadow Monarch",
      "Raiza the Storm Monarch",
      "Thestalos the Firestorm Monarch",
      "Zaborg the Thunder Monarch",
      "Angmarl the Fiendish Monarch",
      "Thestalos the Shadowfire Monarch",
      "Delg the Dark Monarch",
      "Gravekeeper's Vassal",
      "Escalation of the Monarchs",
      "Escher the Frost Vassal",
      "Emperor of the land and sea",
      "Granmarg the Rock Monarch",
    ],
  },
  world_cloaked_in_magical_power: {
    name: "World Cloaked in Magical Power",
    description: ["Sacred Beasts Support", "Yubel"],
    archetypes: [
      "Sacred Beast",
      "Yubel",
      "Old Entity",
      "Summoning Beast",
      "Raviel",
      "Armityle",
    ],
    cards: [
      "Nightmare Throne",
      "Samsara D Lotus",
      "Nightmare Pain",
      "Eternal Favorite",
      "Gruesome Grave Squirmer",
      "Geistgrinder Golem",
      "Mature Chronicle",
      "Elder Entity N'tss",
      "Phantom of Chaos",
      "Uria, Lord of Searing Flames",
      "Hamon, Lord of Striking Thunder",
      "Dark Beckoning Beast",
      "Fallen Paradise",
      "Cerulean Skyfire",
      "Hyper Blaze",
      "Phantasm Emperor Trilojig",
      "The Wicked Dreadroot",
      "The Wicked Eraser",
      "Phantom Skyblaster",
      "Divine Serpent Geh",
      "Divine Evolution",
      "Opening of the Spirit Gates",
      "Outer Entity Nyarla",
      "Mad Reloader",
      "Grave Squirmer",
      "Tragoedia",
      "Chaos Core",
      "Phantasmal Martyrs",
      "The Seal of Orichalcos",
      "Forbidden Trapezohedron",
      "Dreamland",
      "Dimension Fusion Destruction",
      "Hate Buster",
      "Forbidden Apocrypha",
    ],
  },
  neo_space_comrades: {
    name: "Neo Space Comrades",
    description: ["Elemental HERO"],
    archetypes: ["Neo-Spacian", "Neos", "Neo Space"],
    cards: [
      "Cross Keeper",
      "Instant Contact",
      "EN Wave",
      "Battle of Sleeping Spirits",
      "Over Fusion",
      "Miracle Contact",
      "Generation Next",
      "Next",
      "Convert Contact",
      "Contact Out",
      "Double Hero Attack",
      "Contact Gate",
      "Common Soul",
      "Elemental HERO Neos Kluger",
      "Common Soul",
      "Common Soul",
      "Common Soul",
      "Common Soul",
      "Common Soul",
      "Common Soul",
    ],
  },
  stardust_ties: {
    name: "Stardust Ties",
    description: ["Stardust", "Synchron",],
    archetypes: ["Stardust", "Synchron"],
    cards: [
      "Shooting Quasar Dragon",
      "Cosmic Blazar Dragon",
      "Tuning",
      "Duel Link Dragon, the Duel Dragon",
      "Shooting Star Dragon",
      "Shooting Riser Dragon",
      "Starlight Road",
      "Jet Warrior",
      "Righty Driver",
      "Lefty Driver",
      "Doppelwarrior",
      "Cosmic FLare",
      "Scarred Warrior",
      "Gravity Warrior",
      "Debris Dragon",
      "Level Warrior",
      "Sonic Warrior",
      "Rush Warrior",
      "Limit Overdrive",
      "Starlight Junktion",
      "Necroid Synchro",
      "Synchro Chase",
      "Shooting Star",
      "Stardust Flash",
      "Converging Wishes",
    ],
  },
  pearlescent_cyber_dragons: {
    name: "Pearlescent Cyber Dragons",
    description: ["Cyber Dragon"],
    archetypes: ["Cyber Dragon", "Cyberdark", "Chimeratech"],
    cards: [
      "Limiter Removal",
      "Lightning Storm",
      "Cyber Jormungardr",
      "Heosvarog the mechanical Dawn",
      "Evolution End Burst",
      "Cyber End Dragon",
      "Cyber Twin Dragon",
      "Cyber Eternity Dragon",
      "Power Bond",
      "Overload Fusion",
      "Cybernetic Fusion Support",
      "",
    ],
  },
  abyssal_underworld: {
    name: "Abyssal Underworld",
    description: ["Vendread", "Skull Servant", "Zombie Support"],
    archetypes: ["Vendread", "Wight", "Skull Servant"], // I promise this is necessary lmao
    cards: [
      "Dark Necromancer",
      "Vulcarrion the Rotting Phoenix",
      "Uni-Zombie",
      "Doomking Balerdroch",
      "Zombie World",
      "Necroworld Banshee",
      "Glow-Up Bloom",
      "Zombie Necronize",
      "Jack-o-Bolan",
      "Revived King Ha Des",
      "Zombie Master",
      "Plaguespreader Zombie",
      "Pain Painter",
      "Tatsunecro",
      "Zombie Power Struggle",
      "Return of the Zombies",
    ],
    exclude_cards: [
      "Flame Ghost",
      "Zombie Warrior",
      "Tri-Wight",
    ],
  },
  dragonmaid_to_order: {
    name: "Dragonmaid-to-Order",
    description: ["Dragonmaid"],
    archetypes: ["Dragonmaid"],
  },
  raging_thunder: {
    name: "Raging Thunder",
    description: ["Thunder Dragon"],
    archetypes: ["Thunder Dragon"],
  },
  fiendish_plaything: {
    name: "Fiendish Plaything",
    description: ["Fluffal"],
    archetypes: ["Frightfur", "Fluffal", "Edge Imp"],
  },
  toon_kingdom: {
    name: "Toon Kingdom",
    description: ["Toon"],
    archetypes: ["Toon"],
  },
  nebula_cyclone: {
    name: "Nebula Cyclone",
    description: ["Galaxy-Eyes"],
    archetypes: ["Galaxy-Eyes", "Photon", "Tachyon", "Galaxy"],
  },
  shackles_of_smoldering_wrath: {
    name: "Shackles of Smoldering Wrath",
    description: ["Unchained", "Fiend Support"],
    archetypes: ["Unchained"],
  },
  space_insurrection: {
    name: "Space Insurrection",
    description: ["Kozmo", "Psychic/Machine"],
    archetypes: ["Kozmo"],
  },
  one_turn_kill: {
    name: "One-Turn-Kill",
    description: ["Numeron"],
    archetypes: ["Numeron"],
  },
  clash_of_ruins: {
    name: "Clash of Ruins",
    description: ["Ancient Gear", "Machina"],
    archetypes: ["Ancient Gear", "Machina"],
  },

  a_dance_dedicated_to_the_Heavens: {
    name: "A Dance Dedicated to the Heavens",
    description: ["Mikanko", "Guardian", "Equip Support"],
    archetypes: ["Mikanko", "Bamboo Sword"],
    cards: [
      "Hidden Armory",
      "Armory Call",
      "Celestial Sword - Eatos",
      "Guardian Eatos",
      "Guardian Dreadscythe",
      "Power of the Guardians",
      "Guardian Grarl",
      "Reaper Scythe - Dreadscythe",
      "Guardian Elma",
      "Guardian Ceal",
      "Guardian Baou",
      "Guardian Kay'est",
      "Guardian Tryce",
      "Shooting Star Bow - Ceal",
      "Gravity Axe - Grarl",
      "Wicked-Breaking Flamberge - Baou",
      "Rod of Silence - Kay'est",
      "Twin Swords of Flashing light - Tryce",
    ],
  },
  a_full_course_of_magic: {
    name: "A Full Course of Magic",
    description: ["Nouvelles", "Suship"],
    archetypes: ["Nouvelles", "Suship", "Recipe", "Burger"],
    cards: [
      "Instant Fusion",
      "Angry Burger",
      "Ready Fusion",
      "Sea Monster of Theseus",
      "Patissciel Couverture",
      "Painful Decision",
      "Voici la Carte (Today's Menu)",
      "Concours de Cuisine (Culinary Confrontation)",
      "Fusion Duplication",
      "Number 50: Blackship of Corn",
      "Manju of the Ten Thousand Hands",
      "Monster Express",
      "Xyz Align",
      "Xyz Reborn",
      "Painful Escape",
      "Hungry Burger",
      "Cattycorn",
      "Sour Scheduling - Red Vinegar Vamoose",
    ],
  },
  a_song_of_zephyr_and_petals: {
    name: "A Song of Zephyr and Petals",
    description: ["Melodious", "Windwitch"],
    archetypes: ["Melodious", "Windwitch"],
    cards: [
      "Brilliant Rose",
      "Feedran, the Winds of Mischief",
      "Fairy Wind",
      "Lost Wind",
      "Crystal Rose",
      "Pianissimo",
    ],
  },
  a_warrior_of_seething_anger: {
    name: "A Warrior of Seething Anger",
    description: ["Kashtira"],
    archetypes: ["Kashtira"],
    cards: [
      "Macro Cosmos",
      "Different Dimension Ground",
      "Number 11: Big Eye",
      "Red-Eyes Flare Metal Dragon",
      "Dimensional Fissure",
      "Replicard LAD",
      "Additional Mirror Level 7",
      "Pressured Planet Wraitsoth",
      "Trivikarma",
      "Number 28: Titanic Moth",
      "Dark Armed, the Dragon of Annihilation",
      "Infinitrack Mountain Smasher",
      "Number 76: Harmonizer Gradielle",
      "D.D.R. - Different Dimension Reincarnation",
      "Xyz Block",
      "Stall Turn",
    ],
  },
    advanced_warriors: { //This pack SUCKS
    name: "Advanced Warriors",
    description: ["Igknight", "Majespecter", "Dinomist", "Amorphage"],
    archetypes: ["Igknight", "Majespecter", "Dinomist", "Amorphage"],
    cards: [
      "Majester Paladin, the Ascending Dracoslayer",
      "Ignister Prominence, the Blasting Dracoslayer",
      "Dinoster Power, the Mighty Dracoslayer",
      "Master Peace, the True Dracoslayer",
      "Amorphactor Pain, the Imagination Dracoverlord",
      "Luster Pendulum, the Dracoslayer",
      "Draco Face-Off",
      "Lector Pendulum, the Dracoverlord",
    ],
    exclude_cards: [
      "Igknight Reload",
      "Igknight Burst",
      "Igknight Margrave",
      "Igknight Paladin",
      "Igknight Squire",
      "Igknight Veteran",
      "Majespecter Supercell",
      "Majespecter Sonics",
      "Majespecter Gust",
      "Majespecter Draco - Ryu",
      "Majespecter Porcupine - Yamarashi",
      "Majespecter Fox - Kyubi",
      "Majespecter Toad - Ogama",
      "Majespecter Orthrus - Nue",
      "Majespecter Unicorn - Kirin",
      "Majespecter Wind",
      "Dinomist Plesios",
      "Dinomist Eruption",
      "Dinomist Brachion",
      "Dinomist Stegosaur",
      "Amorphage Lechery",
      "Amorphage Lysis",
      "Amorphage Pride",
      "Amorphage Greed",

    ],
  },
  adventure_of_mystical_etchings: {
    name: "Adventure of Mystical Etchings",
    description: ["Generaider", "Runick"],
    archetypes: ["Generaider", "Runick"],
    cards: [
      "Nine-Lives Cat",
      "Cloudcastle",
      "Trias Hierarchia",
      "Xyz Align",
      "Number 92: Heart-eartH Dragon",
      "Number 53: Heart-eartH",
      "Number C92: Heart-eartH Chaos Dragon",
    ],
  },
  agathokakologically_whispered_fates: {
    name: "Agathokakologically Whispered Fates",
    description: ["Vaalmonica", "Majespecter"],
    archetypes: ["Vaalmonica", "Majespecter"],
    cards: [
       "Majesty Pegasus, the Dracoslayer",
       "Lightning Chidori",
       "Protecting Spirit Loagaeth",
       "Stained Glass of Light & Dark",
       "Ebon Sun",
       "Spiritual Wind Art - Miyabi",
       "Sargasso the D.D. Battlefield",
       "Gingerbread House",
       "Summon Storm",
       "Loop of Destruction",
    ],
    exclude_cards: [
      "Majespecter Supercell",
      "Majespecter Sonics",
      "Majespecter Gust",
      "Majespecter Fox - Kyubi",
      "Majespecter Toad - Ogama",
    ],
  },
  ai_omniscience: {
    name: "AI Omniscience",
    description: ["@Ignister"],
    archetypes: ["@Ignister", "A.I."],
    cards: [
      "Firewall Saber Dragon",
      "Code Igniter",
      "Linkslayer",
      "Linguriboh",
    ],
  },
  altered_heraldry: {
    name: "Altered Heraldry",
    description: ["Heraldic Beast", "Generic CXyz Monsters"],
    archetypes: ["Heraldic", "Heraldry"],
    cards: [
      "Rank-Up-Magic Argent Chaos Force",
      "Norito the Moral Leader",
      "Skypalace Gangaridai",
      "Marshalling Field",
      "Fairy Cheer Girl",
      "Mechquipped Angineer",
      "CXyz Mechquipped Djinn Angeneral",
      "CXyz Simon the Great Moral Leader",
      "Comics Hero King Arthur",
      "CXyz Comics Hero Legend Arthur",
      "Battlecruiser Dianthus",
      "CXyz Battleship Cherry Blossom",
      "Resurgam Xyz",
      "Number 92: Heart-eartH Dragon",
      "Number 53: Heart-eartH",
      "Coach King Giantrainer",
      "CXyz Dark Fairy Cheer Girl",
      "CXyz Coach Lord Ultimatrainer",
      "Number C92: Heart-eartH Chaos Dragon",
      "Garbage Ogre",
      "Garbage Lord",
    ],
    exclude_cards: [
      "Heraldic Beast Gryphon",
      "Heraldic Beast Stad Whale",
      "Number 69: Heraldry Crest - Shatter Stream",
      "Number 69: Heraldry Crest - Dark Matter Demolition",
      "Flash of Heraldry",
    ],
  },
  artistic_angel: {
    name: "Artistic Angel",
    description: ["Weather Painter", "Solfachord"],
    archetypes: ["The Weather", "Solfachord"],
    cards: [
      "Maple Maiden",
      "Ret-time Reviver Emit-ter",
      "Number 76: Harmonizer Gradielle",
      "Cupid Volley",
      "Cupid Dunk",
      "Cupid Serve",
      "Cupid Fore",
      "Rain Bozu",
    ],
  },
  astral_trinity_of_gods: {
    name: "Astral Trinity of Gods",
    description: ["Nordic"],
    archetypes: ["Nordic", "Aesir"],
    cards: [
      "The Golden Apples",
      "Gleipnir, the Fetters of Fenrir",
      "Gotterdammerung",
      "March Towards Ragnarok",
      "The Nordic Lights",
      "Divine Relic Mjollnir",
      "Solemn Authority",
      "Odin's Eye",
    ],
    exclude_cards: [
      "Nordic Relic Svalinn",
      "Nordic Beast Gullinbursti",
      "Nordic Smith Ivaldi",
      "Nordic Relic Hlidskjalf",
    ],
  },
  atonements_end: {
    name: "Atonement's End",
    description: ["Snake-Eye", "Azamina"],
    archetypes: ["Diabell", "Sinful Spoils"],
    cards: [
      "Snake-Eye Birch",
      "Startling Stare of the Snake-Eyes",
      "Divine Temple of the Snake-Eye",
      "Dramatic Snake-Eye Chase",
      "Snake-Eyes Vengeance Dragon",
      "Azamina",
      "Witch of the White Forest",
      "Goblin Bikers Gone Bonkers",
      "Silvera, Wolf Tamer of the White Forest",
      "Rciela, Sinister Soul of the White Forest",
      "Poplar of the White Forest",
      "Saint Azamina",
      "Azamina Debtors",
      "Woes of the White Forest",
      "Talons of Shurilane",
      "Golgoil the Steel Seismic Smasher",
      "Queen Azamina",
      "Eye of Illusion",
      "Azamina Determination",
      "Beware the White Forest",
      "Scourge of the White Forest",
    ],
    exclude_cards: [
      "Snake-Eyes Diabellstar",
      "Diabellze the Original Sinkeeper",
      "Diabell, Queen of the White Forest",
      "Elzette, Azamina of the White Forest",
      "WANTED: Seeker of Sinful Spoils",
      "Original Sinful Spoils - Snake-Eye",
      "The Hallowed Azamina",
      "Deception of the Sinful Spoils",

    ],
  },
  awakening_of_the_ancients: {
    name: "Awakening of the Ancients",
    description: ["Artifact", "Guardian"],
    archetypes: ["Artifact"],
    cards: [
      "Guardian Eatos",
      "Double-Edged Sword",
      "Guardian Dreadscythe",
      "Hidden Armory",
      "Power of the Guardians",
      "Armory Call",
      "Arsenal Summoner",
      "Guardian Grarl",
      "Megamorph",
      "Big Bang Shot",
      "Unstable Evolution",
      "Celestial Sword - Eatos",
      "Reaper Scythe - Dreadscythe",
      "Moon Mirror Shield",
      "Guardian Elma",
      "Guardian Ceal",
      "Guardian Baou",
      "Guardian Kay'est",
      "Guardian Tryce",
      "Shooting Star Bow - Ceal",
      "Gravity Axe - Grarl",
      "Wicked-Breaking Flamberge - Baou",
      "Rod of Silence - Kay'est",
      "Twin Swords of Flashing Light - Tryce",
      "Guarded Treasure",
    ],
    exclude_cards: [
      "Artifact Labrys",
      "Artifact Failnaught",
    ],
  },
  beastly_claws_of_terror: {
    name: "Beastly Claws of Terror",
    description: ["Scareclaw"],
    archetypes: ["Scareclaw"],
    cards: [
      "Quaking Mirror Force",
      "Book of Moon",
      "Swords of Concealing Light",
      "Memory Loss",
      "Floodgate Trap Hole",
      "Break Off Trap Hole",
      "Murmur of the Forest",
      "Tackle Crusader",
      "Sphere Kuriboh",
      "Star Power!!",
      "Bunch of Beast Bodies",
      "Visas Starfrost",
      "Book of Eclipse",
      "Book of Lunar Eclipse",
      "Clear New World"
    ],
  },
  beasts_of_the_inferno: {
    name: "Beasts of the Inferno",
    description: ["Volcanic", "Hazy Flame"],
    archetypes: ["Volcanic", "Hazy", "Blaze Accelerator"],
    cards: [
      "Bonfire",
      "Oil",
      "Fire Ejection",
      "Fire Recovery",
      "Star Mine",
      "Vulcan the Divine",
      "Lava Golem",
      "Gren Maju Da Eiza",
      "Firebrand Hymnist",
      "Fire Fighting Daruma Doll",
      "Fencing Fire Ferret",
      "Fire Cracker",
      "Royal Firestorm Guards",
      "Fire Trooper",
      "Flame Tiger",
      "Bonfire Colossus",
      "Hinezumi Hanabi",
      "Soul of Fire",
      "Wild Fire",
      "Firewall",
    ],
    exclude_cards: [
      "Blaze Cannon",
    ],
  },
  beetle_troops_roll_out: {
    name: "Beetle Troops Roll Out",
    description: ["Beetrooper", "Inzektor"],
    archetypes: ["Beetrooper", "Inzektor"],
    cards: [
      "Seraphim Papillion",
      "Primitive Butterfly",
      "Smoke Mosquito",
      "Number 28: Titanic Moth",
      "Scary Moth",
      "Parasite Paranoid",
      "Dragonbite",
      "Shinobi Insect Hagakuremino",
      "Resonance Insect",
      "Variable Form",
    ],
    exclude_cards:
    [
      "Beetrooper Fly & Sting",
      "Heavy Beetrooper Mighty Neptune",
      "Beetrooper Assault Roller",
      "Beetrooper Light Flapper",
    ],
  },
  beloved_dolls: {
    name: "Beloved Dolls",
    description: ["Madolche", "Doll Monster"],
    archetypes: ["Madolche"],
    cards: [
      "Toy Box",
      "Toy Soldier",
      "Toy Tank",
      "Number 22: Zombiestein",
      "Princess Cologne",
      "Doll Happiness",
      "Clara & Rushka, the Ventriloduo",
      "Cross-Sheep",
      "Number 29: Mannequin Cat",
      "Box of Friends",
      "Zombowwow",
      "Grandpa Demetto",
      "Boycotton",
      "Mimikuril",
      "Doll Monster Miss Mädchen",
      "Doll Monster Bear-Bear",
      "Doll House",
    ],
  },
  blazing_fortitude: {
    name: "Blazing Fortitude",
    description: ["Salamangreat"],
    archetypes: ["Salamangreat"],
    cards: [
      "Code of Soul",
      "Phoenix Gearblade",
    ],
  },
  blazing_vitality: {
    name: "Blazing Vitality",
    description: ["Flame Swordsman", "Metalmorph"],
    archetypes: ["Flame Swordsman"],
    cards: [
      "Flametongue the Burning Blade",
      "Red-Eyes Black Fullmetal Dragon",
      "Metal Illusionist",
      "Courageous Crimson Chevalier Bradamante",
      "Mirage Swordsman",
      "Pyrite Knight",
      "Metalzoa X",
      "Red-Eyes Metal Claws Dragon",
      "Incoming Machine!",
      "Double Dai",
      "Max Metalmorph",
      "Infernoble Knight - Roland",
      "Fire Flint Lady",
      "Giltia the D. Knight - Soul Spear",
      "Dragon Nails",
      "Magnum Shield",
      "Gearbreed",
      "\"Infernoble Arms - Durendal\"",
      "\"Infernoble Arms - Joyeuse\"",
      "Rare Metalmorph",
      "Red-Eyes Black Metal Dragon",
      "Zoa the Fiendish Beast",
      "Phoenix Gearblade",
      "Metalmorph",
      "Time Engine",
      "Flame Coating Metalmorph",
    ],
  },
  blazing_warriors: {
    name: "Blazing Warriors",
    description: ["Heroic", "Battlin' Boxer"],
    archetypes: ["Heroic", "Battlin'"],
    cards: [
      "Rank-Up-Magic - The Seventh One",
      "Stoic Challenge",
      "Number 54: Lion Heart",
      "Jolt Counter",
      "Xyz Block",
      "Last Counter",
    ],
    exclude_cards: [
      "Heroic Champion - Magnum Excalibur",
      "Ring Announcer",
      "Battlin' Boxing Cross Counter",
      "Battlin' Boxer King Dempsey",
      "Battlin' Boxer Uppercutter",
      "Battlin' Boxer Chief Second",
      "Battlin' Boxer Promoter",
      "Number C79: Battlin' Boxer General Kaiser",
    ],
  },
  blooming_in_adversity: {
    name: "Blooming in Adversity",
    description: ["Aroma", "Rikka"],
    archetypes: ["Aroma", "Rikka"],
    cards: [
      "Lonefire Blossom",
      "Tytannial, Princess of Camellias",
      "Staysailor Romarin",
      "Queen of Thorns",
      "Number 87: Queen of the Night",
      "Botanical Lion",
      "Botanical Girl",
      "Talaya, Princess of Cherry Blossoms",
      "Mariña, Princess of Sunflowers",
      "Chirubimé, Princess of Autumn Leaves"
    ],
    exclude_cards: [
      "Rikka Konkon",
      "Rikka Princess",
    ],
  },
  bonkers_bikers_wild_wheels: {
    name: "Bonkers Bikers' Wild Wheels",
    description: ["Goblin Biker", "Wind-Up"],
    archetypes: ["Goblin Biker", "Wind-Up"],
    cards: [
      "Upstart Goblin",
      "Goblin Circus",
      "Goblin's Crazy Beast",
      "Goblin Freefall Squad",
      "Good Goblin Housekeeping",
    ],
  },
  bujins_vault_of_heaven: {
    name: "Bujin's Vault of Heaven",
    description: ["Bujin"],
    archetypes: ["Bujin"],
    cards: [
    ],
  exclude_cards: [
    "Bujin Hiruko",
    "Bujin Hirume",

  ],
}
};

/**
 * Custom / Individual Cards to add to the card pool
 * Add your own custom card definitions here!
 *
 * Each card must follow this exact structure:
 * {
 *     id: Unique Number (e.g. 99999901),
 *     name: "Card Name",
 *     type: "Card Type (e.g. Effect Monster, Spell Card, Trap Card)",
 *     desc: "Card text description",
 *     archetype: "Optional Archetype Name (for Secret Pack filtering)",
 *     md_rarity: "UR", // Rarity short code: "UR", "SR", "R", or "N"
 *     card_images: [
 *         {
 *             image_url: "Full card image URL",
 *             image_url_small: "Small card image URL for grid"
 *         }
 *     ]
 * }
 */

/**
 * Custom / Individual Cards to exclude / remove from all pack pools.
 * Add card names (string) or card IDs (number) to filter them out of
 * both the General Master Pool and Secret Packs.
 *
 * Example:
 * const EXCLUDED_CARDS = [
 *     "Jerry Beans Man", // Exclude Jerry Beans Man by name
 *     101                // Exclude Ash Blossom by its ID
 * ];
 */
const EXCLUDED_CARDS = [
  // Add card names or card IDs here to exclude them from the simulator pools
  "Divine Dragon Token", 
  // Banlist Start
  "Dimension Shifter", 
  "PSY-Framelord Omega", 
  "Synchro Overtake", 
  "Abyss Dweller",
  "Agido the Ancient Sentinel",
  "Amazoness Archer",
  "Apollousa, Bow of the Goddess",
  "Archlord Kristya",
  "Artifact Mjollnir",
  "Artifact Scythe",
  "Barrier Statue of the Drought",
  "Barrier Statue of the Stormwinds",
  "Beatrice, Lady of the Eternal",
  "Blackwing - Gofu the Vague Shadow",
  "Cannon Soldier",
  "Cannon Soldier MK-2",
  "Catapult Turtle",
  "Chaos Ruler, the Chaotic Magical Dragon",
  "Crystron Halqifibrax",
  "Cyber-Stein",
  "Dandylion",
  "Djinn Releaser of Rituals",
  "Elder Entity Norden",
  "Evilswarm Ouroboros",
  "Fiber Jar",
  "Fishborg Blaster",
  "Fossil Dyna Pachycephalo",
  "Gimmick Puppet Nightmare",
  "Grinder Golem",
  "Guardragon Agarpain",
  "Guardragon Elpy",
  "Hot Red Dragon Archfiend King Calamity",
  "Ido the Supreme Magical Force",
  "Jowgen the Spiritualist",
  "Kelbek the Ancient Vanguard",
  "Knightmare Corrupter Iblee",
  "Lavalval Chain",
  "Level Eater",
  "Linkross",
  "Lyrilusc - Independent Nightingale",
  "Magical Scientist",
  "Maliss ＜Q＞ Red Ransom",
  "Mind Master",
  "Naturia Rosewhip",
  "Number 16: Shock Master",
  "Number 41: Bagooska the Terribly Tired Tapir",
  "Number 67: Pair-a-Dice Smasher",
  "Number 86: Heroic Champion - Rhongomyniad",
  "Number 89: Diablosis the Mind Hacker",
  "Number 95: Galaxy-Eyes Dark Matter Dragon",
  "Number S0: Utopic ZEXAL",
  "Outer Entity Azathot",
  "Performapal Five-Rainbow Magician",
  "Phantasmal Lord Ultimitl Bishbaalkin",
  "Phoenixian Cluster Amaryllis",
  "Substitoad",
  "Superheavy Samurai Soulbreaker Armor",
  "Tearlaments Merrli",
  "Tempest Magician",
  "The Tyrant Neptune",
  "Toadally Awesome",
  "Toon Cannon Soldier",
  "Topologic Gumblar Dragon",
  "True King of All Calamities",
  "Union Carrier",
  "Wind-Up Hunter",
  "Butterfly Dagger - Elma",
  "Called by the Grave",
  "Card of Demise",
  "Card of Safe Return",
  "Cold Wave",
  "Confiscation",
  "Delinquent Duo",
  "Dimension Fusion",
  "Divine Sword - Phoenix Blade",
  "Giant Trunade",
  "Graceful Charity",
  "Harpie's Feather Storm",
  "Kaiser Colosseum",
  "Last Will",
  "Mass Driver",
  "Mirage of Nightmare",
  "Mystic Mine",
  "Obedience Schooled",
  "Painful Choice",
  "Pot of Greed",
  "Pot of Prosperity",
  "Premature Burial",
  "Primeval Planet Perlereino",
  "Ryzeal Cross",
  "Secret Village of the Spellcasters",
  "Set Rotation",
  "Smoke Grenade of the Thief",
  "Soul Charge",
  "Terraforming",
  "The Forceful Sentry",
  "Appointer of the Red Lotus",
  "Anti-Spell Fragrance",
  "Branded Expulsion",
  "Imperial Order",
  "Last Turn",
  "Life Equalizer",
  "Magical Explosion",
  "Return from the Different Dimension",
  "Royal Oppression",
  "Self-Destruct Button",
  "Sixth Sense",
  "Summon Limit",
  "Trap Dustshoot",
  "Ultimate Offering",
  "Vanity's Emptiness",
  // Banlist End
];
